swagger: '2.0'
info:
  title: API Registry
  version: "0.1"
  description: |
    Use this [RESTful](http://en.wikipedia.org/wiki/Representational_state_transfer) 
    API to register your APIs with the [API Portal](http://api.software.slb.com).

    ## Specify a Unique ID
    The 'api_id' is how you will create and access your API registration. The 'api_id'
    is your own ID so be sure to include a prefix for the id so your id doesn't conflict with 
    other services. You should include version numbers in the api_id (only you see) if your want 
    support multiple versions of the API. Include the version number in the name so the user's of the
    API can find the appropriate documentation.

    ## When to register
    Use the 'PUT api/{api_id}' to register your API. The best time to register your
    API is during deployment of your service. 

    '''sh 
    curl -X PUT --header 'Content-Type: application/json' --header 'Accept: text/html' -d '{
      "api_type": "private",
      "apiexamples_url": "https://appspot.com/api/v1/examples/",
      "apiquickstart_url": "https://appspot.com/api/v1/qs/",
      "apireference_url": "https://appspot.com/api/v1/ui/",
      "base_url": "https://appspot.com:3001/api/v1",
      "name": "API Name",
    }' 'https://slb-extensibility-demo.appspot.com/api/OwnerAPIName'
    '''
    
consumes:
  - application/json
produces:
  - application/json
security:
  # enable OAuth protection for all REST endpoints
  # (only active if the TOKENINFO_URL environment variable is set)
  - oauth2: [uid]
paths:
  /apis:
    get:
      tags: [APIs]
      operationId: app.get_apis
      summary: Get all apis
      parameters:
        - name: api_type
          description: "Query by the type of the API. Types allowed: Public,Private."
          in: query
          type: string
          pattern: "^[a-zA-Z0-9]*$"
        - name: limit
          in: query
          type: integer
          minimum: 0
          default: 100
      responses:
        200:
          description: Return APIs
          schema:
            type: array
            items:
              $ref: '#/definitions/API'
  /api/{api_id}:
    get:
      tags: [APIs]
      operationId: app.get_api
      summary: Get a single api
      parameters:
        - $ref: '#/parameters/api_id'
      responses:
        200:
          description: Return API
          schema:
            $ref: '#/definitions/API'
        404:
          description: API does not exist
    put:
      tags: [APIs]
      operationId: app.put_api
      summary: Create or update a API
      parameters:
        - $ref: '#/parameters/api_id'
        - name: api
          in: body
          schema:
            $ref: '#/definitions/API'
      responses:
        200:
          description: API updated
        201:
          description: New API created
    delete:
      tags: [APIs]
      operationId: app.delete_api
      summary: Remove a API
      parameters:
        - $ref: '#/parameters/api_id'
      responses:
        204:
          description: API was deleted
        404:
          description: API does not exist


parameters:
  api_id:
    name: api_id
    description: API's Unique identifier
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-]+$"

definitions:
  API:
    type: object
    required:
      - name
      - id
      - api_type
    properties:
      id:
        type: string
        description: "Unique identifier for the API. Be sure to include a unique prefix to keep your APIs separate from others."
        example: "Department.ID1"
        readOnly: true
      name:
        type: string
        description: "The name of the API"
        example: "API Datastore"
        minLength: 1
        maxLength: 100
      api_type:
        type: string
        description: "Type of API. For example: public, private, underDevelopment"
        example: "private"
        minLength: 1 
      base_url:
        description: "Base URL of Service endpoints"
        example: "https://appspot.com:3001/api/v1"
        minLength: 1
      apireference_url:
        description: "URL to API reference documentation"
        example: "https://appspot.com/api/v1/ui/"
        minLength: 1
      apiquickstart_url:
        description: "URL to API quick start documentation"
        example: "https://appspot.com/api/v1/qs/"
      apiexamples_url:
        description: "URL to examples of usage"
        example: "https://appspot.com/api/v1/examples/"  
      created:
        type: string
        format: date-time
        description: Creation time
        example: "2015-07-07T15:49:51.230+02:00"
        readOnly: true
      updated:
        type: string
        format: date-time
        description: Last update time
        example: "2015-07-07T15:49:51.230+02:00"
        readOnly: false
      
securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    scopes:
      uid: Unique identifier of the user accessing the service.
