swagger: '2.0'
info:
  title: API Registry Service
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
security:
  # enable OAuth protection for all REST endpoints
  # (only active if the TOKENINFO_URL environment variable is set)
  - oauth2: [uid]
paths:
  /APIs:
    get:
      tags: [APIs]
      operationId: app.get_apis
      summary: Get all APIs
      parameters:
        - name: api_type
          in: query
          type: string
          pattern: "^[a-zA-Z0-9]*$"
        - name: limit
          in: query
          type: integer
          minimum: 0
          default: 100
      responses:
        200:
          description: Return APIs
          schema:
            type: array
            items:
              $ref: '#/definitions/API'
  /APIs/{api_id}:
    get:
      tags: [APIs]
      operationId: app.get_api
      summary: Get a single API
      parameters:
        - $ref: '#/parameters/api_id'
      responses:
        200:
          description: Return API
          schema:
            $ref: '#/definitions/API'
        404:
          description: API does not exist
    put:
      tags: [APIs]
      operationId: app.put_api
      summary: Create or update a API
      parameters:
        - $ref: '#/parameters/api_id'
        - name: api
          in: body
          schema:
            $ref: '#/definitions/API'
      responses:
        200:
          description: API updated
        201:
          description: New API created
    delete:
      tags: [APIs]
      operationId: app.delete_api
      summary: Remove a API
      parameters:
        - $ref: '#/parameters/api_id'
      responses:
        204:
          description: API was deleted
        404:
          description: API does not exist


parameters:
  api_id:
    name: api_id
    description: API's Unique identifier
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-]+$"

definitions:
  API:
    type: object
    required:
      - name
      - api_type
      - base_url
      - doc_url
    properties:
      id:
        type: string
        description: Unique identifier
        example: "123"
        readOnly: true
      name:
        type: string
        description: API's name
        example: "API Registry"
        minLength: 1
        maxLength: 100
      api_type:
        type: string
        description: Kind of API
        example: "public"
        minLength: 1
      doc_url:
        type: string
        description: URL for documentation
        example: "public"
        minLength: 1
      base_url:
        type: string
        description: Base of URL for Service
        example: "public"
        minLength: 1
      created:
        type: string
        format: date-time
        description: Creation time
        example: "2015-07-07T15:49:51.230+02:00"
        readOnly: true


securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    scopes:
      uid: Unique identifier of the user accessing the service.
