swagger: '2.0'
info:
  title: API Datastore
  version: "0.1"
  description: List of APIs usable by other developers \
    Registration put apis/{api_id}
consumes:
  - application/json
produces:
  - application/json
security:
  # enable OAuth protection for all REST endpoints
  # (only active if the TOKENINFO_URL environment variable is set)
  - oauth2: [uid]
paths:
  /apis:
    get:
      tags: [APIs]
      operationId: app.get_apis
      summary: Get all apis
      parameters:
        - name: api_type
          description: "Query by the type of the API. Types allowed: Public,Private."
          in: query
          type: string
          pattern: "^[a-zA-Z0-9]*$"
        - name: limit
          in: query
          type: integer
          minimum: 0
          default: 100
      responses:
        200:
          description: Return APIs
          schema:
            type: array
            items:
              $ref: '#/definitions/API'
  /api/{api_id}:
    get:
      tags: [APIs]
      operationId: app.get_api
      summary: Get a single api
      parameters:
        - $ref: '#/parameters/api_id'
      responses:
        200:
          description: Return API
          schema:
            $ref: '#/definitions/API'
        404:
          description: API does not exist
    put:
      tags: [APIs]
      operationId: app.put_api
      summary: Create or update a API
      parameters:
        - $ref: '#/parameters/api_id'
        - name: api
          in: body
          schema:
            $ref: '#/definitions/API'
      responses:
        200:
          description: API updated
        201:
          description: New API created
    delete:
      tags: [APIs]
      operationId: app.delete_api
      summary: Remove a API
      parameters:
        - $ref: '#/parameters/api_id'
      responses:
        204:
          description: API was deleted
        404:
          description: API does not exist


parameters:
  api_id:
    name: api_id
    description: API's Unique identifier
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-]+$"

definitions:
  API:
    type: object
    required:
      - name
      - id
      - api_type
    properties:
      id:
        type: string
        description: "Unique identifier for the API. Be sure to include a unique prefix to keep your APIs separate from others."
        example: "Department.ID1"
        readOnly: true
      name:
        type: string
        description: "The name of the API"
        example: "API Datastore"
        minLength: 1
        maxLength: 100
      api_type:
        type: string
        description: "Type of API. For example: public, private, underDevelopment"
        example: "private"
        minLength: 1 
      base_url:
        description: "Base URL of Service endpoints"
        example: "https://appspot.com:3001/api/v1"
        minLength: 1
      apireference_url:
        description: "URL to API reference documentation"
        example: "https://appspot.com/api/v1/ui/"
        minLength: 1
      apiquickstart_url:
        description: "URL to API quick start documentation"
        example: "https://appspot.com/api/v1/qs/"
      apiexamples_url:
        description: "URL to examples of usage"
        example: "https://appspot.com/api/v1/examples/"  
      created:
        type: string
        format: date-time
        description: Creation time
        example: "2015-07-07T15:49:51.230+02:00"
        readOnly: true
      updated:
        type: string
        format: date-time
        description: Last update time
        example: "2015-07-07T15:49:51.230+02:00"
        readOnly: false
      
securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    scopes:
      uid: Unique identifier of the user accessing the service.
